### ISSUE TITLE
Missing ERD on Project Proposal - Rejected

### ISSUE THREAD

**Issue by Scifiler-sys** [220118-Reston-NET/WeSharper-P2#5]

**Comment by Scifiler-sys** [comment]
For storing images, look into Azure Blob storage. The RDBMS database we use doesn't have a fun time storing an actual image. You can also leverage other Apis that store images for you if you want.

**Comment by Scifiler-sys** [comment]
When finding a new friend user story, will that be based on some algorithm such as same interest or your close friends are also the same friends as them or just a simple search feature that looks up the friend based on some property like name?

**Comment by kirasn** [comment]
It's not based on the name 😂
